import React, { useRef } from 'react';
export default function GraphCanvas({ nodes = [], edges = [], isDirected = false, activeEdge = null, width = 820, height = 460, onNodeMove }) {
  const svgRef = useRef(null); const dragRef = useRef(null);
  const point = event => { const box = svgRef.current.getBoundingClientRect(); return { x: Math.max(22, Math.min(width - 22, (event.clientX - box.left) * width / box.width)), y: Math.max(22, Math.min(height - 22, (event.clientY - box.top) * height / box.height)) }; };
  const move = event => { if (!dragRef.current) return; const p = point(event); onNodeMove?.(dragRef.current, p.x, p.y, false); };
  const end = event => { if (!dragRef.current) return; const id = dragRef.current; const p = point(event); dragRef.current = null; onNodeMove?.(id, p.x, p.y, true); };
  return <div style={{ width: '100%', overflowX: 'auto', display: 'flex', justifyContent: 'center', padding: '.5rem 0' }}><svg ref={svgRef} viewBox={`0 0 ${width} ${height}`} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{ width: '100%', maxWidth: `${width}px`, height: `${height}px`, background: 'var(--bg-surface)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-subtle)', touchAction: 'none' }}>
    <defs><marker id="arrowhead" markerWidth="8" markerHeight="8" refX="25" refY="4" orient="auto"><polygon points="0 0, 8 4, 0 8" fill="#64748b" /></marker></defs>
    {edges.map((edge, index) => { const u = nodes.find(n => n.id === edge.u); const v = nodes.find(n => n.id === edge.v); if (!u || !v) return null; const active = activeEdge && ((activeEdge.u === edge.u && activeEdge.v === edge.v) || (!isDirected && activeEdge.u === edge.v && activeEdge.v === edge.u)); const color = edge.status === 'traversing' || active ? '#f59e0b' : '#cbd5e1'; return <g key={`${edge.u}-${edge.v}-${index}`}><line x1={u.x} y1={u.y} x2={v.x} y2={v.y} stroke={color} strokeWidth={active ? 3.5 : 2} markerEnd={isDirected ? 'url(#arrowhead)' : undefined} /><g transform={`translate(${(u.x + v.x) / 2}, ${(u.y + v.y) / 2})`}><rect x="-14" y="-10" width="28" height="20" rx="4" fill="#fff" stroke={color} /><text dy="4" textAnchor="middle" fontSize="11" fontWeight="700">{edge.weight}</text></g></g>; })}
    {nodes.map(node => { let fill = '#fff'; if (node.color) fill = node.color; else if (node.status === 'settled') fill = '#10b981'; else if (node.status === 'current') fill = '#f59e0b'; return <g key={node.id} transform={`translate(${node.x}, ${node.y})`} onPointerDown={event => { event.currentTarget.setPointerCapture?.(event.pointerId); dragRef.current = node.id; }} style={{ cursor: 'grab' }}><circle r="22" fill={fill} stroke="#64748b" strokeWidth="2" /><text textAnchor="middle" dy="5" fontSize="13" fontWeight="700" fill={fill === '#fff' ? '#0f172a' : '#fff'}>{node.label}</text>{node.dist !== undefined && <text textAnchor="middle" dy="36" fontSize="11" fill="#2563eb">{node.dist === Infinity ? '∞' : `d=${node.dist}`}</text>}</g>; })}
  </svg></div>;
}
